import { useState } from "react";
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
  Legend, ResponsiveContainer, Cell
} from "recharts";

const CONDITIONS = {
  full_pipeline: { label: "Full pipeline",  color: "#1D9E75", desc: "Decomposer + SymPy + LLM verifier" },
  no_sympy:      { label: "No SymPy",       color: "#378ADD", desc: "Decomposer + LLM verifier only" },
  raw_groq:      { label: "Raw Groq",       color: "#E24B4A", desc: "Single generator call, unverified" },
};

const TIER_ORDER = ["algebra", "number_theory", "olympiad"];
const TIER_LABELS = { algebra: "Algebra", number_theory: "Number theory", olympiad: "Olympiad" };

function parseSummary(data) {
  return data?.summary?.rows || [];
}

function UploadZone({ onLoad }) {
  return (
    <div style={{ padding: "3rem 1rem", textAlign: "center" }}>
      <i className="ti ti-chart-bar" style={{ fontSize: 36, color: "var(--color-text-tertiary)", display: "block", marginBottom: "1rem" }} aria-hidden="true" />
      <p style={{ fontSize: 15, fontWeight: 500, color: "var(--color-text-primary)", margin: "0 0 0.5rem" }}>
        Load your eval_results.json
      </p>
      <p style={{ fontSize: 12, color: "var(--color-text-secondary)", margin: "0 0 1.5rem" }}>
        Generated by: <code>python eval_harness.py --tiers algebra --conditions full_pipeline no_sympy raw_groq</code>
      </p>
      <label style={{
        display: "inline-flex", alignItems: "center", gap: 8,
        padding: "0.55rem 1.2rem",
        background: "var(--color-background-secondary)",
        border: "1px solid var(--color-border-primary)",
        borderRadius: "var(--border-radius-md)",
        cursor: "pointer", fontSize: 13, color: "var(--color-text-primary)",
      }}>
        <i className="ti ti-upload" aria-hidden="true" />
        Choose file
        <input type="file" accept=".json" style={{ display: "none" }}
          onChange={e => {
            const f = e.target.files[0]; if (!f) return;
            const r = new FileReader();
            r.onload = ev => { try { onLoad(JSON.parse(ev.target.result)); } catch { alert("Invalid JSON"); } };
            r.readAsText(f);
          }}
        />
      </label>
    </div>
  );
}

function Card({ children, style = {} }) {
  return (
    <div style={{
      background: "var(--color-background-secondary)",
      border: "1px solid var(--color-border-tertiary)",
      borderRadius: "var(--border-radius-lg)",
      padding: "1.25rem",
      ...style,
    }}>
      {children}
    </div>
  );
}

function StatBadge({ label, value, sub, color }) {
  return (
    <div style={{ flex: 1, minWidth: 110 }}>
      <Card>
        <div style={{ fontSize: 11, color: "var(--color-text-secondary)", marginBottom: 4 }}>{label}</div>
        <div style={{ fontSize: 22, fontWeight: 500, color: color || "var(--color-text-primary)" }}>{value}</div>
        {sub && <div style={{ fontSize: 11, color: "var(--color-text-tertiary)", marginTop: 2 }}>{sub}</div>}
      </Card>
    </div>
  );
}

// ── Chart: Convergence by tier ────────────────────────────────────────────────
function ConvergenceChart({ rows }) {
  const conditions = [...new Set(rows.map(r => r.condition))];
  const tiers = TIER_ORDER.filter(t => rows.some(r => r.tier === t));

  const data = tiers.map(t => {
    const entry = { tier: TIER_LABELS[t] || t };
    conditions.forEach(c => {
      const r = rows.find(x => x.tier === t && x.condition === c);
      entry[c] = r ? Math.round(r.convergence_rate * 100) : 0;
    });
    return entry;
  });

  return (
    <Card>
      <h3 style={{ fontSize: 13, fontWeight: 500, margin: "0 0 1rem" }}>Convergence rate by tier (%)</h3>
      <p style={{ fontSize: 11, color: "var(--color-text-secondary)", margin: "0 0 1rem" }}>
        For raw Groq: 100% means "produced output" (not verified). For full/no_sympy: means proof passed verification.
      </p>
      <ResponsiveContainer width="100%" height={210}>
        <BarChart data={data} margin={{ top: 0, right: 8, left: -20, bottom: 0 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border-tertiary)" />
          <XAxis dataKey="tier" tick={{ fontSize: 11, fill: "var(--color-text-secondary)" }} />
          <YAxis domain={[0, 100]} tick={{ fontSize: 11, fill: "var(--color-text-secondary)" }} />
          <Tooltip
            contentStyle={{ background: "var(--color-background-primary)", border: "1px solid var(--color-border-primary)", borderRadius: 8, fontSize: 12 }}
            formatter={(v, name) => [`${v}%`, CONDITIONS[name]?.label || name]}
          />
          <Legend iconSize={10} wrapperStyle={{ fontSize: 11 }} formatter={n => CONDITIONS[n]?.label || n} />
          {conditions.map(c => (
            <Bar key={c} dataKey={c} fill={CONDITIONS[c]?.color || "#888"} radius={[3,3,0,0]} />
          ))}
        </BarChart>
      </ResponsiveContainer>
    </Card>
  );
}

// ── Chart: Mean iterations ────────────────────────────────────────────────────
function IterationsChart({ rows }) {
  const conditions = [...new Set(rows.map(r => r.condition))].filter(c => c !== "raw_groq");
  const tiers = TIER_ORDER.filter(t => rows.some(r => r.tier === t));

  const data = tiers.map(t => {
    const entry = { tier: TIER_LABELS[t] || t };
    conditions.forEach(c => {
      const r = rows.find(x => x.tier === t && x.condition === c);
      entry[c] = r ? r.mean_iterations : 0;
    });
    return entry;
  });

  return (
    <Card>
      <h3 style={{ fontSize: 13, fontWeight: 500, margin: "0 0 0.25rem" }}>Mean iterations to converge</h3>
      <p style={{ fontSize: 11, color: "var(--color-text-secondary)", margin: "0 0 1rem" }}>
        Fewer iterations = more efficient. Lower is better. Raw Groq excluded (always 1 iteration).
      </p>
      <ResponsiveContainer width="100%" height={200}>
        <BarChart data={data} margin={{ top: 0, right: 8, left: -20, bottom: 0 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border-tertiary)" />
          <XAxis dataKey="tier" tick={{ fontSize: 11, fill: "var(--color-text-secondary)" }} />
          <YAxis tick={{ fontSize: 11, fill: "var(--color-text-secondary)" }} />
          <Tooltip contentStyle={{ background: "var(--color-background-primary)", border: "1px solid var(--color-border-primary)", borderRadius: 8, fontSize: 12 }}
            formatter={(v, name) => [v.toFixed(1), CONDITIONS[name]?.label || name]} />
          <Legend iconSize={10} wrapperStyle={{ fontSize: 11 }} formatter={n => CONDITIONS[n]?.label || n} />
          {conditions.map(c => (
            <Bar key={c} dataKey={c} fill={CONDITIONS[c]?.color || "#888"} radius={[3,3,0,0]} />
          ))}
        </BarChart>
      </ResponsiveContainer>
    </Card>
  );
}

// ── Chart: SymPy value-add ────────────────────────────────────────────────────
function SympyValueChart({ rows }) {
  const fullRows = rows.filter(r => r.condition === "full_pipeline");
  if (!fullRows.length) return null;

  const data = TIER_ORDER.filter(t => fullRows.some(r => r.tier === t)).map(t => {
    const r = fullRows.find(x => x.tier === t);
    return {
      tier: TIER_LABELS[t] || t,
      "SymPy intercepts": r?.total_sympy_intercepts || 0,
      "LLM verifier fails": r?.total_llm_verifier_fails || 0,
    };
  });

  return (
    <Card>
      <h3 style={{ fontSize: 13, fontWeight: 500, margin: "0 0 0.25rem" }}>SymPy value-add (full pipeline only)</h3>
      <p style={{ fontSize: 11, color: "var(--color-text-secondary)", margin: "0 0 1rem" }}>
        SymPy intercepts = algebraic errors caught <em>before</em> LLM verifier ran. This is your key result —
        SymPy catches errors that would cost an expensive LLM call.
      </p>
      <ResponsiveContainer width="100%" height={190}>
        <BarChart data={data} margin={{ top: 0, right: 8, left: -20, bottom: 0 }}>
          <CartesianGrid strokeDasharray="3 3" stroke="var(--color-border-tertiary)" />
          <XAxis dataKey="tier" tick={{ fontSize: 11, fill: "var(--color-text-secondary)" }} />
          <YAxis tick={{ fontSize: 11, fill: "var(--color-text-secondary)" }} allowDecimals={false} />
          <Tooltip contentStyle={{ background: "var(--color-background-primary)", border: "1px solid var(--color-border-primary)", borderRadius: 8, fontSize: 12 }} />
          <Legend iconSize={10} wrapperStyle={{ fontSize: 11 }} />
          <Bar dataKey="SymPy intercepts" fill="#1D9E75" radius={[3,3,0,0]} />
          <Bar dataKey="LLM verifier fails" fill="#378ADD" radius={[3,3,0,0]} />
        </BarChart>
      </ResponsiveContainer>
    </Card>
  );
}

// ── Per-problem breakdown table ───────────────────────────────────────────────
function ResultsTable({ data }) {
  const [tierFilter, setTierFilter] = useState("all");
  const [condFilter, setCondFilter] = useState("all");

  const results = data?.results || [];
  const filtered = results.filter(r =>
    (tierFilter === "all" || r.tier === tierFilter) &&
    (condFilter === "all" || r.condition === condFilter)
  );

  const tiers = [...new Set(results.map(r => r.tier))];
  const conds = [...new Set(results.map(r => r.condition))];

  const pillStyle = (active) => ({
    padding: "0.2rem 0.7rem", borderRadius: 999, fontSize: 11, cursor: "pointer",
    border: "1px solid var(--color-border-secondary)",
    background: active ? "var(--color-background-tertiary)" : "transparent",
    color: active ? "var(--color-text-primary)" : "var(--color-text-secondary)",
  });

  return (
    <Card>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "0.75rem", flexWrap: "wrap", gap: 8 }}>
        <h3 style={{ fontSize: 13, fontWeight: 500, margin: 0 }}>Per-problem results</h3>
        <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>
          <button style={pillStyle(tierFilter==="all")} onClick={() => setTierFilter("all")}>All tiers</button>
          {tiers.map(t => <button key={t} style={pillStyle(tierFilter===t)} onClick={() => setTierFilter(t)}>{TIER_LABELS[t]||t}</button>)}
          <span style={{ color: "var(--color-border-secondary)" }}>|</span>
          <button style={pillStyle(condFilter==="all")} onClick={() => setCondFilter("all")}>All conditions</button>
          {conds.map(c => <button key={c} style={pillStyle(condFilter===c)} onClick={() => setCondFilter(c)}>{CONDITIONS[c]?.label||c}</button>)}
        </div>
      </div>
      <div style={{ overflowX: "auto" }}>
        <table style={{ width: "100%", borderCollapse: "collapse", fontSize: 11 }}>
          <thead>
            <tr style={{ borderBottom: "1px solid var(--color-border-secondary)" }}>
              {["Problem","Tier","Condition","Status","Iters","SymPy↑","LLM fails","Time(s)"].map(h => (
                <th key={h} style={{ textAlign: "left", padding: "0.35rem 0.5rem", fontWeight: 500, color: "var(--color-text-secondary)", whiteSpace: "nowrap" }}>{h}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {filtered.map((r, i) => {
              const cond = CONDITIONS[r.condition] || {};
              const statusColor = r.status === "verified" ? "#1D9E75" : r.status === "timeout" ? "#EF9F27" : "#E24B4A";
              return (
                <tr key={i} style={{ borderBottom: "1px solid var(--color-border-tertiary)" }}>
                  <td style={{ padding: "0.35rem 0.5rem", fontFamily: "var(--font-mono)", fontSize: 10 }}>{r.problem_id}</td>
                  <td style={{ padding: "0.35rem 0.5rem", color: "var(--color-text-secondary)" }}>{TIER_LABELS[r.tier]||r.tier}</td>
                  <td style={{ padding: "0.35rem 0.5rem" }}>
                    <span style={{ display: "inline-flex", alignItems: "center", gap: 4 }}>
                      <span style={{ width: 7, height: 7, borderRadius: "50%", background: cond.color || "#888", flexShrink: 0 }} />
                      {cond.label || r.condition}
                    </span>
                  </td>
                  <td style={{ padding: "0.35rem 0.5rem", color: statusColor, fontWeight: 500 }}>{r.status}</td>
                  <td style={{ padding: "0.35rem 0.5rem" }}>{r.iterations}</td>
                  <td style={{ padding: "0.35rem 0.5rem", color: r.sympy_intercepts > 0 ? "#1D9E75" : "var(--color-text-tertiary)", fontWeight: r.sympy_intercepts > 0 ? 500 : 400 }}>
                    {r.sympy_intercepts}
                  </td>
                  <td style={{ padding: "0.35rem 0.5rem" }}>{r.llm_verifier_fails}</td>
                  <td style={{ padding: "0.35rem 0.5rem", color: "var(--color-text-secondary)" }}>{r.elapsed_seconds?.toFixed(1)}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
        {filtered.length === 0 && (
          <p style={{ textAlign: "center", color: "var(--color-text-tertiary)", padding: "1rem", fontSize: 12 }}>No results match the current filter.</p>
        )}
      </div>
    </Card>
  );
}

// ── Main dashboard ────────────────────────────────────────────────────────────
export default function EvalDashboard() {
  const [data, setData] = useState(null);

  if (!data) return <UploadZone onLoad={setData} />;

  const rows = parseSummary(data);
  const results = data.results || [];
  const conditions = [...new Set(rows.map(r => r.condition))];

  const getCondStat = (cond, metric) => {
    const condRows = rows.filter(r => r.condition === cond);
    if (!condRows.length) return null;
    const vals = condRows.map(r => r[metric]);
    return vals.reduce((a, b) => a + b, 0) / vals.length;
  };

  const fullConv   = getCondStat("full_pipeline", "convergence_rate");
  const noSympyConv = getCondStat("no_sympy", "convergence_rate");
  const rawConv    = getCondStat("raw_groq", "convergence_rate");
  const sympyLift  = fullConv != null && noSympyConv != null
    ? ((fullConv - noSympyConv) * 100).toFixed(1) : null;
  const totalSympyHits = rows.filter(r => r.condition === "full_pipeline")
    .reduce((s, r) => s + (r.total_sympy_intercepts || 0), 0);

  return (
    <div style={{ padding: "1rem 0", display: "flex", flexDirection: "column", gap: "1rem" }}>

      {/* Header */}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", flexWrap: "wrap", gap: 8 }}>
        <div>
          <h2 style={{ margin: 0, fontSize: 17, fontWeight: 500 }}>Empirical ablation analytics</h2>
          <p style={{ margin: "3px 0 0", fontSize: 11, color: "var(--color-text-secondary)" }}>
            {results.length} problem runs · Date: {data.timestamp?.slice(0, 10)} · Conditions: {conditions.map(c => CONDITIONS[c]?.label || c).join(", ")}
          </p>
        </div>
        <button onClick={() => setData(null)} style={{
          fontSize: 11, padding: "0.3rem 0.8rem",
          border: "1px solid var(--color-border-secondary)",
          borderRadius: "var(--border-radius-md)",
          background: "transparent", cursor: "pointer",
          color: "var(--color-text-secondary)",
        }}>
          <i className="ti ti-refresh" aria-hidden="true" style={{ marginRight: 4 }} />
          Load new file
        </button>
      </div>

      {/* Condition legend */}
      <div style={{ display: "flex", gap: "0.75rem", flexWrap: "wrap" }}>
        {Object.entries(CONDITIONS).filter(([k]) => conditions.includes(k)).map(([k, v]) => (
          <div key={k} style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 11, color: "var(--color-text-secondary)" }}>
            <span style={{ width: 10, height: 10, borderRadius: "50%", background: v.color, flexShrink: 0 }} />
            <strong style={{ color: "var(--color-text-primary)", fontWeight: 500 }}>{v.label}</strong>
            — {v.desc}
          </div>
        ))}
      </div>

      {/* Stat cards */}
      <div style={{ display: "flex", gap: "0.75rem", flexWrap: "wrap" }}>
        {fullConv != null && <StatBadge label="Full pipeline convergence" value={`${(fullConv*100).toFixed(0)}%`} color="#1D9E75" />}
        {noSympyConv != null && <StatBadge label="No-SymPy convergence" value={`${(noSympyConv*100).toFixed(0)}%`} color="#378ADD" />}
        {sympyLift != null && (
          <StatBadge
            label="SymPy improvement"
            value={`${sympyLift > 0 ? "+" : ""}${sympyLift}pp`}
            sub="full vs no-sympy"
            color={parseFloat(sympyLift) >= 0 ? "#1D9E75" : "#E24B4A"}
          />
        )}
        <StatBadge label="Total SymPy intercepts" value={totalSympyHits} sub="errors caught before LLM" color="#EF9F27" />
      </div>

      <ConvergenceChart rows={rows} />
      <IterationsChart rows={rows} />
      <SympyValueChart rows={rows} />
      <ResultsTable data={data} />
    </div>
  );
}
