"""
LangGraph agent: Decomposer → Generator → SymPy Verification → Verifier loop with convergence check.
Neuro-symbolic proof generation with SymPy verification + LLM verification.
WOW FACTOR PLOTTING EDITION.
"""
from __future__ import annotations

import asyncio
import operator
import os
import re
from typing import Annotated, Literal, TypedDict

import sympy
from sympy.parsing.sympy_parser import parse_expr, standard_transformations, implicit_multiplication_application
from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage
from langgraph.graph import END, StateGraph

# ── State ────────────────────────────────────────────────────────────────────
class ProofState(TypedDict):
    problem:            str
    subgoals:           str          # strategic subgoals generated by decomposer
    current_proof:      str
    plot_data:          str          # NEW: JSON plot data for wow-factor rendering
    summary:            str
    feedback:           str
    sympy_feedback:     str          # symbolic check results
    iteration:          int
    consecutive_passes: int
    max_iterations:     int
    required_passes:    int
    status:             str
    history:            Annotated[list, operator.add]

# ── LLM helpers ──────────────────────────────────────────────────────────────
def _llm_gen():
    llm = ChatGroq(
        model="llama-3.3-70b-versatile",
        temperature=0.4,
        max_tokens=4096,
        api_key=os.environ.get("GROQ_API_KEY", ""),
    )
    fallbacks = []
    if os.environ.get("GROQ_API_KEY1"):
        fallbacks.append(ChatGroq(model="llama-3.3-70b-versatile", temperature=0.4, max_tokens=4096, api_key=os.environ["GROQ_API_KEY1"]))
    if os.environ.get("GROQ_API_KEY2"):
        fallbacks.append(ChatGroq(model="llama-3.3-70b-versatile", temperature=0.4, max_tokens=4096, api_key=os.environ["GROQ_API_KEY2"]))
    return llm.with_fallbacks(fallbacks) if fallbacks else llm

def _llm_ver():
    llm = ChatGroq(
        model="llama-3.3-70b-versatile",
        temperature=0.0,
        max_tokens=4096,
        api_key=os.environ.get("GROQ_API_KEY", ""),
    )
    fallbacks = []
    if os.environ.get("GROQ_API_KEY1"):
        fallbacks.append(ChatGroq(model="llama-3.3-70b-versatile", temperature=0.0, max_tokens=4096, api_key=os.environ["GROQ_API_KEY1"]))
    if os.environ.get("GROQ_API_KEY2"):
        fallbacks.append(ChatGroq(model="llama-3.3-70b-versatile", temperature=0.0, max_tokens=4096, api_key=os.environ["GROQ_API_KEY2"]))
    return llm.with_fallbacks(fallbacks) if fallbacks else llm

def _extract_tag(text: str, tag: str) -> str | None:
    m = re.search(rf"<{tag}>(.*?)</{tag}>", text, re.DOTALL | re.IGNORECASE)
    return m.group(1).strip() if m else None

def _snippet(proof: str, n: int = 200) -> str:
    return proof[:n] + "…" if len(proof) > n else proof

# ── SymPy Symbolic Checker ───────────────────────────────────────────────────
def sympy_check_steps(proof_text: str) -> tuple[bool, str]:
    checks = re.findall(r"<check>(.*?)</check>", proof_text, re.DOTALL | re.IGNORECASE)
    if not checks:
        return True, "No symbolic checks found — skipping SymPy verification."

    errors = []
    passed = []
    transformations = (standard_transformations + (implicit_multiplication_application,))

    for i, raw in enumerate(checks):
        raw = raw.strip()
        if "==" in raw:
            parts = raw.split("==", 1)
        elif "=" in raw:
            parts = raw.split("=", 1)
        else:
            errors.append(f"Step {i+1}: Cannot parse '{raw}' — no equality found.")
            continue

        try:
            lhs_expr = parse_expr(parts[0].strip(), transformations=transformations)
            rhs_expr = parse_expr(parts[1].strip(), transformations=transformations)
            diff = sympy.simplify(lhs_expr - rhs_expr)
            if diff == 0:
                passed.append(f"Step {i+1}: ✓ `{raw}`")
            else:
                errors.append(f"Step {i+1}: ✗ `{raw}` — simplifies to {diff} ≠ 0")
        except Exception as e:
            passed.append(f"Step {i+1}: skipped (could not parse: {e})")

    summary_lines = passed + errors
    summary = "\n".join(summary_lines)
    if errors:
        summary = f"SymPy found {len(errors)} algebraic error(s):\n" + summary
    else:
        summary = f"SymPy verified {len(passed)} step(s):\n" + summary

    return len(errors) == 0, summary

# ── Prompts ──────────────────────────────────────────────────────────────────
DECOMPOSER_SYSTEM = """You are a math problem strategist.
Break the given mathematical problem into 2-4 ordered sub-goals/steps that logically together prove the main result.
Output ONLY:
<subgoals>
1. [first sub-goal]
2. [second sub-goal]
...
</subgoals>"""

GENERATOR_SYSTEM = """You are a rigorous mathematical proof writer with the ability to draw interactive plots.

Rules:
1. Every claim must be justified.
2. State every lemma before using it.
3. Use $ for inline math and $$ for block math.
4. CRITICAL: For every algebraic simplification or expansion you perform, wrap it in a <check> tag so it can be verified.
   Format: <check>lhs == rhs</check> (use Python/SymPy syntax).
5. WOW FACTOR PLOTTING: If the problem asks to visualize, plot, or understand a function geometrically, you MUST output a `<plot>` tag containing a valid JSON array of `x` and `y` coordinates. 
   Example: <plot>[{"x": -2, "y": 4}, {"x": -1, "y": 1}, {"x": 0, "y": 0}, {"x": 1, "y": 1}, {"x": 2, "y": 4}]</plot>
   Provide at least 10-15 coordinate points so the curve looks smooth!
6. Work through the provided sub-goals sequentially. Tag the proof section for each sub-goal with `<subgoal n>...</subgoal n>` blocks.

Output format — respond ONLY with:
<proof>
[full proof here, with <check> tags for algebraic steps and <subgoal n> tags for each subgoal section]
</proof>
<plot>
[optional JSON array of points if visualizing a function is helpful]
</plot>
<summary>
[one-paragraph plain-English summary of the key idea]
</summary>"""

GENERATOR_RETRY_SYSTEM = GENERATOR_SYSTEM + """

You are on iteration {iteration}. Previous attempts failed.
Study EVERY piece of feedback below and fix ALL reported errors.
Pay special attention to SymPy feedback — those are provably wrong steps."""

VERIFIER_SYSTEM = """You are a mathematical proof verifier. Find ACTUAL logical errors.

Check for:
1. Logical gaps or unjustified leaps
2. Missing lemmas or prerequisites
3. Incorrect theorem citations
4. Edge cases not handled
5. Circular reasoning
6. Any step that contradicts the problem statement

Do NOT re-check arithmetic — a separate symbolic checker already verified algebraic steps.
Focus on LOGICAL and STRUCTURAL correctness.

Output format — respond ONLY with:
<scratchpad>
[your line-by-line analysis]
</scratchpad>
<verdict>PASS</verdict>
OR
<verdict>FAIL</verdict>
<flaws>
[numbered list of every logical flaw, with exact references]
</flaws>"""

# ── Nodes ────────────────────────────────────────────────────────────────────
async def decomposer_node(state: ProofState) -> dict:
    llm = _llm_gen()
    response = await llm.ainvoke([
        SystemMessage(content=DECOMPOSER_SYSTEM),
        HumanMessage(content=f"## Problem\n\n{state['problem']}")
    ])
    raw = response.content
    subgoals = _extract_tag(raw, "subgoals") or raw
    return {"subgoals": subgoals}


async def generator_node(state: ProofState) -> dict:
    llm = _llm_gen()
    iteration = state.get("iteration", 0)

    system = (
        GENERATOR_SYSTEM if iteration == 0
        else GENERATOR_RETRY_SYSTEM.replace("{iteration}", str(iteration))
    )

    user_content = f"## Problem\n\n{state['problem']}\n"
    if state.get("subgoals"):
        user_content += f"\n## Sub-goals to Achieve\n\n{state['subgoals']}\n"
    if state.get("sympy_feedback"):
        user_content += f"\n## Symbolic Checker Feedback\n\n{state['sympy_feedback']}\n"
    if state.get("feedback") and state["feedback"] != "Proof passed verification.":
        user_content += f"\n## Logic Verifier Feedback\n\n{state['feedback']}\n"

    if state.get("history"):
        prior = "\n\n".join(
            f"### Attempt {h['iteration']}\nSymPy: {h.get('sympy_feedback','')}\nLogic: {h.get('feedback','')}"
            for h in state["history"] if h.get("feedback") or h.get("sympy_feedback")
        )
        if prior:
            user_content += f"\n## All Prior Feedback\n\n{prior}\n"

    response = await llm.ainvoke([SystemMessage(content=system), HumanMessage(content=user_content)])
    raw = response.content

    proof = _extract_tag(raw, "proof") or raw
    plot_data = _extract_tag(raw, "plot") or ""
    summary = _extract_tag(raw, "summary") or ""

    return {
        "current_proof": proof,
        "plot_data": plot_data,
        "summary": summary,
        "iteration": iteration + 1,
    }


async def sympy_node(state: ProofState) -> dict:
    loop = asyncio.get_event_loop()
    try:
        passed, feedback = await asyncio.wait_for(
            loop.run_in_executor(None, sympy_check_steps, state["current_proof"]),
            timeout=10.0
        )
    except asyncio.TimeoutError:
        passed = False
        feedback = "SymPy found 1 algebraic error(s):\nStep 1: ✗ Expression too complex. SymPy timed out. Simplify your math."
    
    return {
        "sympy_feedback": feedback,
        "status": "running" if passed else "sympy_failed",
    }


async def verifier_node(state: ProofState) -> dict:
    if state.get("status") == "sympy_failed":
        history_entry = {
            "iteration": state["iteration"],
            "proof": state["current_proof"],
            "plot_data": state.get("plot_data", ""),
            "summary": state.get("summary", ""),
            "feedback": "SymPy caught algebraic errors — skipped LLM verifier.",
            "sympy_feedback": state.get("sympy_feedback", ""),
            "verdict": "FAIL",
        }
        return {
            "feedback": "Algebraic errors detected by symbolic checker. See sympy_feedback.",
            "consecutive_passes": 0,
            "status": "running" if state["iteration"] < state["max_iterations"] else "failed",
            "history": [history_entry],
        }

    llm = _llm_ver()
    user_content = (
        f"## Problem\n\n{state['problem']}\n\n"
        f"## Proof to Verify\n\n{state['current_proof']}"
    )
    response = await llm.ainvoke([SystemMessage(content=VERIFIER_SYSTEM), HumanMessage(content=user_content)])
    raw = response.content

    verdict_raw = _extract_tag(raw, "verdict") or ""
    flaws = _extract_tag(raw, "flaws") or ""

    passed = verdict_raw.strip().upper() == "PASS"

    if passed:
        new_consecutive = state.get("consecutive_passes", 0) + 1
        feedback = "Proof passed verification."
    else:
        new_consecutive = 0
        feedback = flaws if flaws.strip() else "Unspecified logical errors — see verifier output."

    if new_consecutive >= state["required_passes"]:
        status = "verified"
    elif state["iteration"] >= state["max_iterations"]:
        status = "failed"
    else:
        status = "running"

    history_entry = {
        "iteration": state["iteration"],
        "proof": state["current_proof"],
        "plot_data": state.get("plot_data", ""),
        "summary": state.get("summary", ""),
        "feedback": feedback,
        "sympy_feedback": state.get("sympy_feedback", ""),
        "verdict": "PASS" if passed else "FAIL",
    }

    return {
        "feedback": feedback,
        "consecutive_passes": new_consecutive,
        "status": status,
        "history": [history_entry],
    }

# ── Routing ──────────────────────────────────────────────────────────────────
def route_after_verifier(state: ProofState) -> Literal["generator", "__end__"]:
    return END if state["status"] in ("verified", "failed") else "generator"

def route_after_sympy(state: ProofState) -> Literal["verifier"]:
    return "verifier"

# ── Graph Assembly ────────────────────────────────────────────────────────────
def build_graph():
    builder = StateGraph(ProofState)
    builder.add_node("decomposer", decomposer_node)
    builder.add_node("generator", generator_node)
    builder.add_node("sympy_checker", sympy_node)
    builder.add_node("verifier", verifier_node)

    builder.set_entry_point("decomposer")
    builder.add_edge("decomposer", "generator")
    builder.add_edge("generator", "sympy_checker")
    builder.add_conditional_edges("sympy_checker", route_after_sympy)
    builder.add_conditional_edges("verifier", route_after_verifier)

    return builder.compile()
